### ISSUE TITLE
[youtube subtitles] missing check for None

### ISSUE THREAD

**Issue by NordMike** [thiswillbeyourgithub/wdoc#10]
It seems there is chapter property in info even if there are no chapters in video.

https://github.com/thiswillbeyourgithub/wdoc/blob/f035f224d46e1ea23d6846e01432e93d2d0dd692/wdoc/utils/loaders.py#L2276

**Comment by thiswillbeyourgithub** [comment]
Pushing on dev asap

**Comment by thiswillbeyourgithub** [comment]
Thanks a lot for reporting. Can you check the latest dev please?

**Comment by NordMike** [comment]
This fix works for me.

**Comment by thiswillbeyourgithub** [comment]
Thanks for reporting back. I made a new release to address the 2 issues you created yesterday
