### ISSUE TITLE
No module named 'lazy_import'

### ISSUE THREAD

**Issue by webyacusa** [thiswillbeyourgithub/wdoc#2]
I followed your instructions and when I try to run the sample command to summarize the arstechnica article, I get the following error:

> python -m DocToolsLLM --task="summary" --path="https://arstechnica.com/science/2024/06/to-pee-or-not-to-pee-that-is-a-question-for-the-bladder-and-the-brain/".
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "E:\dev\DocToolsLLM\.venv\Lib\site-packages\DocToolsLLM\__init__.py", line 19, in <module>
    import lazy_import
ModuleNotFoundError: No module named 'lazy_import'

Any Idea what am I missing?

**Comment by thiswillbeyourgithub** [comment]
Hi, Thanks for giving it a try!

1. I just pushed a fix, my bad sorry!

2. I recently became painfully aware of a number of dumb bugs in my code so I modified this project a great deal in the recent days but it's a terrible timing visavis medical school exams. So it's not so stable and API will break from time to time but I still use it very frequently and will push updates to the dev branch. Don't hesitate to open issue if you find bugs and I'll squash them asap but keep in mind that this project has still a lot more planned in the coming months.

Cheers
