### ISSUE TITLE
Cache problem in WSL

### ISSUE THREAD

**Issue by Arn-Thor** [thiswillbeyourgithub/wdoc#8]
I too ran into a problem on WSL. In my case, no matter what I do I get AssertionError: Invalid cache dir location: 'C:\Users\Username\AppData\Local\wdoc\wdoc\Cache'

Installed in a venv for/with pip for python 3.11.

**Comment by thiswillbeyourgithub** [comment]
Hi! Thank you for the interest and taking a look.

I don't have wsl so i'm confident this issue has decent chances of being trivial to fix. Could you share the error trace to help me a bit?

**Comment by thiswillbeyourgithub** [comment]
Hi, I'm on mobile but did a quick fix in termux and pushed to pypi so that should be good now. This was caused by not trusting platformdir and adding assert overzealously. Sorry!

And thank you for bringing this to my attention, that's the only way for me to find those bugs!

**Comment by Arn-Thor** [comment]
Thanks for giving this problem your attention! The error's gone and I can see the help instructions.
